#!/bin/bash

set -xe

# source the common build functions
SCRIPT_DIR=$(dirname "$0")
source "${SCRIPT_DIR}/ios_build_functions.sh"

setup_build_environment
pushd "${ROOT_PATH}/External/openssl-apple"
sed -i '' 's/IOS_MIN_SDK_VERSION=\"11.0\"/IOS_MIN_SDK_VERSION=\"10.3\"/' build-libssl.sh
./build-libssl.sh --version=1.1.1d --targets="ios-cross-armv7 ios-cross-armv7s ios-sim-cross-x86_64 ios64-cross-arm64"
cp -r bin/*.sdk "${INSTALL_PATH}"
cp -r "include/openssl" "${INSTALL_PATH}/include/"
cp lib/libcrypto-iPhone.a "${INSTALL_PATH}/lib/libcrypto.a"
cp lib/libssl-iPhone.a "${INSTALL_PATH}/lib/libssl.a"
popd
